--- #YAML:1.0
name:                Algorithm-Nhash
version:             0.001
abstract:            Exim nhash algorithm
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
