---
abstract: 'Exim nhash algorithm'
author:
  - 'Peter Corlett <abuse@cabal.org.uk>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-Nhash
requires:
  Carp: 0
  perl: 5.006
  vars: 0
version: 0.002
